//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PheoBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPN
    {
        public int MACTPN { get; set; }
        public Nullable<int> MAPN { get; set; }
        public Nullable<double> DONGIANHAP { get; set; }
        public Nullable<int> SOLUONGNHAP { get; set; }
        public Nullable<int> MASP { get; set; }
    
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
