//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PheoBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTDDHs = new HashSet<CTDDH>();
            this.CTPNs = new HashSet<CTPN>();
            this.DONDATHANGs = new HashSet<DONDATHANG>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<double> DONGIA { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> LUOTXEM { get; set; }
        public Nullable<int> MALOAI { get; set; }
        public string HINHANH { get; set; }
        public string HINHANH1 { get; set; }
        public string HINHANH2 { get; set; }
        public Nullable<bool> XOA { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDDH> CTDDHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPN> CTPNs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONDATHANG> DONDATHANGs { get; set; }
        public virtual LOAISP LOAISP { get; set; }
    }
}
